version: 2
jobs:
  build:
    working_directory: ~/hello-vue
    docker:
      - image: circleci/node:10.15.1
      #- image: mongo:3.4.4
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
      
      - setup_remote_docker

      - run: 
          command: |
            set -x 
            docker build -t appmanagm/hello-vue:lastest .

      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push appmanagm/hello-vue:lastest